/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConversionRateOptimierungRouteImport } from './routes/conversion-rate-optimierung'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as ShopifyEntwicklungRouteImport } from './routes/shopify-entwicklung'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversionRateOptimierungRoute =
  ConversionRateOptimierungRouteImport.update({
    id: '/conversion-rate-optimierung',
    path: '/conversion-rate-optimierung',
    getParentRoute: () => rootRouteImport,
  } as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopifyEntwicklungRoute = ShopifyEntwicklungRouteImport.update({
  id: '/shopify-entwicklung',
  path: '/shopify-entwicklung',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conversion-rate-optimierung': typeof ConversionRateOptimierungRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/shopify-entwicklung': typeof ShopifyEntwicklungRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conversion-rate-optimierung': typeof ConversionRateOptimierungRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/shopify-entwicklung': typeof ShopifyEntwicklungRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conversion-rate-optimierung': typeof ConversionRateOptimierungRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/shopify-entwicklung': typeof ShopifyEntwicklungRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conversion-rate-optimierung'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/shopify-entwicklung'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conversion-rate-optimierung'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/shopify-entwicklung'
  id:
    | '__root__'
    | '/'
    | '/conversion-rate-optimierung'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/shopify-entwicklung'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConversionRateOptimierungRoute: typeof ConversionRateOptimierungRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  ShopifyEntwicklungRoute: typeof ShopifyEntwicklungRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversion-rate-optimierung': {
      id: '/conversion-rate-optimierung'
      path: '/conversion-rate-optimierung'
      fullPath: '/conversion-rate-optimierung'
      preLoaderRoute: typeof ConversionRateOptimierungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopify-entwicklung': {
      id: '/shopify-entwicklung'
      path: '/shopify-entwicklung'
      fullPath: '/shopify-entwicklung'
      preLoaderRoute: typeof ShopifyEntwicklungRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConversionRateOptimierungRoute: ConversionRateOptimierungRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  ShopifyEntwicklungRoute: ShopifyEntwicklungRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
